# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': '触发报警后的动作类型', 'verbose_name_plural': '触发报警后的动作类型'},
        ),
        migrations.AlterModelOptions(
            name='actionoperation',
            options={'verbose_name': '触发报警后的具体动作', 'verbose_name_plural': '触发报警后的具体动作'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': '存储报警及其它事件日志', 'verbose_name_plural': '存储报警及其它事件日志'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机信息', 'verbose_name_plural': '主机信息'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': '主机维护表', 'verbose_name_plural': '主机维护表'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '服务名称', 'verbose_name_plural': '服务名称'},
        ),
        migrations.AlterModelOptions(
            name='serviceindex',
            options={'verbose_name': '指标表', 'verbose_name_plural': '指标表'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': '模板', 'verbose_name_plural': '模板'},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器'},
        ),
        migrations.AlterModelOptions(
            name='triggerexpression',
            options={'verbose_name': '触发器表达式', 'verbose_name_plural': '触发器表达式'},
        ),
    ]
